# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('capitalName', models.CharField(max_length=100)),
                ('correncyname', models.CharField(max_length=100)),
            ],
        ),
    ]
