# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagURL', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('capitalName', models.CharField(max_length=100)),
                ('currencyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='flagdata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.GeoData'),
        ),
    ]
