# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagdata',
            name='flagURL',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='capitalName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='countryName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='currencyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
