# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geo',
            old_name='correncyname',
            new_name='currencyname',
        ),
    ]
