# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170616_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagdata',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.GeoData'),
        ),
    ]
