# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20170616_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagdata',
            name='country',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='geo.GeoData'),

        ),
        migrations.AlterField(
            model_name='flagdata',
            name='flagURL',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='countryName',
            field=models.CharField(max_length=100),
        ),
    ]
