# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20170605_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geo',
            old_name='currencyname',
            new_name='currencyName',
        ),
    ]
